/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104641-g9dd104f6e2-20211123"
#endif /* AVUTIL_FFVERSION_H */
